### ISSUE TITLE
Exception: Could not find connections for all subworkflow inputs

### ISSUE THREAD

**Issue by lecorguille** [usegalaxy-eu/ena-cog-uk-wfs#20]
I'm playing around with a toy example provided [here](https://github.com/usegalaxy-eu/ena-cog-uk-wfs/blob/main/docs/data_import.md): 
```
# THIS IS A HEADER
ERX5451093: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/000/ERR5739250/ERR5739250_1.fastq.gz
ERX5451093: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/000/ERR5739250/ERR5739250_2.fastq.gz
ERX5451093: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/001/ERR5739251/ERR5739251_1.fastq.gz
ERX5451093: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/001/ERR5739251/ERR5739251_2.fastq.gz
ERX5451094: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/005/ERR5739255/ERR5739255_1.fastq.gz
ERX5451094: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/005/ERR5739255/ERR5739255_2.fastq.gz
ERX5451094: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/006/ERR5739256/ERR5739256_1.fastq.gz
ERX5451094: ftp.sra.ebi.ac.uk/vol1/fastq/ERR573/006/ERR5739256/ERR5739256_2.fastq.gz
```
(I have to add a header line because the [line](https://github.com/usegalaxy-eu/ena-cog-uk-wfs/blob/main/bioblend-scripts/ftp_links_to_yaml.py#L249)). Before submit a patch on the doc, I prefer to run the full process.
I plan to make some feedback latter about the easiness of this repo :)

I'm a little stuck not specially with the script themselves but with the workflow.

It's seem that I'm in the case of a [`collection_type: list:list` ](https://github.com/usegalaxy-eu/ena-cog-uk-wfs/blob/main/run_variation.sh#L46-L49). So I have to import the workflow [ARTIC PE variation analysis from nested samples](https://usegalaxy.fr/u/lecorguille/w/artic-pe-variation-analysis-from-nested-samples-imported-from-uploaded-file)

I have an issue:
```
Traceback (most recent call last):
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 195, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 271, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/modules.py", line 509, in execute
    subworkflow_invoker = progress.subworkflow_invoker(trans, step, use_cached_job=use_cached_job)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 483, in subworkflow_invoker
    subworkflow_progress = self.subworkflow_progress(subworkflow_invocation, step, workflow_run_config.param_map)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 510, in subworkflow_progress
    raise Exception("Could not find connections for all subworkflow inputs.")
Exception: Could not find connections for all subworkflow inputs.
galaxy.workflow.run ERROR 2021-06-04 11:09:29,698 [pN:handler1,p:6505,tN:WorkflowRequestMonitor.monitor_thread] Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 195, in invoke
    incomplete_or_none = self._invoke_step(workflow_invocation_step)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 271, in _invoke_step
    use_cached_job=self.workflow_invocation.use_cached_job)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/modules.py", line 509, in execute
    subworkflow_invoker = progress.subworkflow_invoker(trans, step, use_cached_job=use_cached_job)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 483, in subworkflow_invoker
    subworkflow_progress = self.subworkflow_progress(subworkflow_invocation, step, workflow_run_config.param_map)
  File "/shared/ifbstor1/galaxy/server/lib/galaxy/workflow/run.py", line 510, in subworkflow_progress
    raise Exception("Could not find connections for all subworkflow inputs.")
Exception: Could not find connections for all subworkflow inputs.
galaxy.workflow.scheduling_manager DEBUG 2021-06-04 11:09:29,753 [pN:handler1,p:6505,tN:WorkflowRequestMonitor.monitor_thread] Workflow invocation [4454] scheduled
```

I'm not really familliar with the nest collection. Here is my history :  https://usegalaxy.fr/u/lecorguille/h/emergen-testdatatab
Is it in good or bad shape ?

**Comment by lecorguille** [comment]
I check the tools within the workflows. 
The only difference between .fr et .eu is Collapse Collection .fr==5.10 et .eu==4.2

**Comment by lecorguille** [comment]
As suggested by @mvdbeek 
I launched the WF using the user interface: https://usegalaxy.fr/u/lecorguille/h/emergen-testdatatab---gui 

Not better :/

**Comment by lecorguille** [comment]
Fixed by switching to the version 0.2 [COVID-19-PE-ARTIC-ILLUMINA (v0.2)](https://workflowhub.eu/workflows/110)

**Comment by bgruening** [comment]
Can this be closed @lecorguille

**Comment by bgruening** [comment]
Everything working for FR?

**Comment by lecorguille** [comment]
I was on holiday for 3 weeks. In the meantime, we got our first data from the sequencing platforms.
Unfortunately, although we sent them a protocol, so far it's rather messy and can't be process with our automate.

We will have to put that in shape with them.

About the "meta-workflow" itself, I will resume my progress this week.
